### ISSUE TITLE
Text Speed and Cleanliness

### ISSUE THREAD

**Issue by coreygjerman** [ryangrau/Lone-Warrior#25]
We need to slow down the speed at which the text gets delivered to the screen.  That way the user can read your narrative without needing to necessarily scroll up, etc.

We also need to clean up the text so that looks nice and uniform in the window.

In the library "time" there is a function called "sleep" that will wait for a certain amount of seconds.  So I'd suggest doing an "import sleep from time" thing on top of the functions file (it gets imported to everything, so the sleep function should get imported with it).

Once imported, you can spread out some sleep(some number of seconds) in your text, and it'll make the computer wait between prints.

**Comment by ryangrau** [comment]
check
